### ISSUE TITLE
Question: Member team association fails under special conditions

### ISSUE THREAD

**Issue by tibeer** [opentelekomcloud/ansible-collection-gitcontrol#39]
Scenario:

A new user is added to the org while simultaniously added to existing teams.
Since the user has not accepted the invitation yet, the user cannot be added to the teams.
The wish mentioned in SovereignCloudStack/github-manager#51 suggests to supress the error
and just pass on. The user would be automatically added once a second run of the playbook is triggered.

This would only be a valid solution if the playbook is periodically executed __besides__ execution on merges.
@gtema what do you think?

**Comment by gtema** [comment]
yeah, should work. No objections

**Comment by tibeer** [comment]
are you okay with a patch that suppresses errors on adding org members while also adding them to teams?

**Comment by gtema** [comment]
yes. Maybe add parameter like "ignore_missing_org_member" or something like that

**Comment by tibeer** [comment]
Closed as this cannot be reproduced currently.
